### ISSUE TITLE
playerdata got fucked with 

### ISSUE THREAD

**Issue by soapsofthoneyandmilk** [gcurtiss/protocol3#51] opened 2021-04-04 18:07 UTC
![image](https://user-images.githubusercontent.com/80994262/113517622-f0c24180-9535-11eb-84a4-12894e5ba231.png)
no i did not join in march :/
and yes this is will
i have no idea how to repro this, i just did /stats and saw my jd as march 2021

**Comment by gcurtiss** [comment] 2021-04-04 20:28
this only applies to you and since i can't reproduce it i don't know what to tell you

closing the issue as it is unreproducable

this is not an issue with p3 either, jd is stored by Paper. did you chunkban yourself? using chunk dupes can cause playerdata to get unintentionally reset. i can't help you with this issue because 1. there's no reliable way to change jd 2. there's no way for me to know your original jd even if i was able to change it

**Closed by gcurtiss** 2021-04-04 20:28 UTC
